version: 2

jobs:

  build:

    working_directory: ~/code

    docker:
      - image: circleci/node:8.10

    steps:

      - checkout

      - run: echo 'build'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-node-modules-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-node-modules-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-modules-{{ checksum "package.json" }}

      - run:
          name: linting
          # command: npm run lint -- --format junit -o reports/eslint.xml
          command: node_modules/.bin/eslint --format checkstyle --output-file reports/eslint-checkstyle.xml .

      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

      - run: echo 'comment'

      - restore_cache:
          keys:
            - v1-dependencies-gems-{{ checksum "Gemfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-gems-

      - run:
          name: bundle install
          command: bundle install --jobs=4 --path vendor/bundle
          when: always

      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-gems-{{ checksum "Gemfile" }}

      - run:
          name: comment on pull request
          command: DANGER_GITHUB_API_TOKEN={GITHUB_PULLREQUEST_COMMENT_KEY} bundle exec danger
          when: always

      - persist_to_workspace:

          root: ~/code
          path: reports

  comment:

    working_directory: ~/code

    docker:

      - image: ruby:2.4.1

    steps:

      - checkout

      - attach_workspace:

          at: ~/code

      - run: echo 'comment'

      - run: ls ~/code/reports


workflows:

  version: 2

  build_and_comment:

    jobs:

      - build

      - comment:

          requires:

            - build
