version: 2

jobs:

  build:

    working_directory: ~/code

    docker:
      - image: circleci/node:8.10

    steps:

      - checkout

      - run: echo 'build'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-node-modules-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-node-modules-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-modules-{{ checksum "package.json" }}

      - run: ls

      - run: mkdir reports

      - run:
          name: linting
          # command: npm run lint -- --format junit -o reports/eslint.xml
          command: node_modules/.bin/eslint --format checkstyle --output-file reports/eslint-checkstyle.xml .

      - run:
          name: comment
          command: npm run danger
          when: always

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports

workflows:

  version: 2

  build_and_comment:

    jobs:

      - build
